# Documentation: https://roots.io/trellis/docs/mail/
mail_smtp_server: smtp.google.com:587
mail_admin: daniel@thedjdesign.com
mail_hostname: roots.dev
mail_user: smtp_user
mail_password: "{{ vault_mail_password }}" # Define this variable in group_vars/all/vault.yml
